version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: Ketero
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: topsecret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
