version: '3.8'
services:
  app:
    image: teyouale/nketero:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      ACCESS_TOKEN_SECRET :  "SECRET"
      REFRESH_TOKEN_SECRET : "SECRET"
      PUBLIC_URL : http://localhost:5173
      DATABASE_URL : postgresql://prisma:topsecret@localhost:5432/Ketero?schema=public
      
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: Ketero
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: topsecret
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
